name: Send Email on Push

on:
  push:
    branches:
      - main
      - dev
      - feature/*

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      # Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      # Instalar dependencias (si es necesario)
      - name: Install dependencies
        run: python -m pip install --upgrade pip

      # Ejecutar el script
      - name: Run Python Script
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          BRANCH_NAME: ${{ github.ref_name }}
          REPOSITORY_NAME: ${{ github.repository }}
        run: python send_email.py
